services:
  java_app:
    container_name: java_app
    image: vonhugo/backend_live:0.0.8
    build: . # dureccion donde esta el docketfile
    mem_limit: 512m
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/live
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - APPLICATION_NAME=java_app
    restart: always
    depends_on:
      java_db:
          condition: service_healthy
    volumes:
          - app_logs:/var/logs/java_app  # Montar el volumen en el contenedor
    networks:
      - spring-network

  java_db:
    container_name: java_db
    image: postgres:17.4-alpine
    shm_size: 4gb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: live
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d live"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
          - spring-network
networks:
  spring-network:

volumes:
  pgdata: {} # Volumen para la base de datos
  app_logs: {}  # Volumen para los logs de java_app
